site_name: PyPty (python + ptychography)
theme:
  name: material
  palette:
    - scheme: slate  # dark mode; use 'default' for light mode
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default  # optional toggle for light mode
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: reference/logo.png  # optional path to custom logo
  features:
    - navigation.expand
    - navigation.sections
    - content.code.annotate  # code annotations, e.g., line highlighting
    - content.tabs.link  # linkable tabs

extra_css:
  - stylesheets/custom.css  # custom CSS if you want even more control

nav:
  - Overview & Installation: reference/pypty/pypty.md
  - Guide for creating custom presets: reference/pypty/custom_presets.md
  - Guide for using provided initialization routines: reference/pypty/ini_custom.md
  - API Reference:
      - initialize: reference/pypty/initialize.md
      - dpc: reference/pypty/dpc.md
      - direct_ptychography: reference/pypty/direct_ptychography.md
      - tcbf: reference/pypty/tcbf.md
      - signal_extraction: reference/pypty/signal_extraction.md
      - iterative_ptychography: reference/pypty/iterative_ptychography.md
      - loss_and_direction: reference/pypty/loss_and_direction.md
      - multislice: reference/pypty/multislice.md
      - fft: reference/pypty/fft.md
      - utils: reference/pypty/utils.md
      - vaa: reference/pypty/vaa.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed  # tabs in content
  - pymdownx.details  # collapsible sections

plugins:
  - search
  - autorefs  # auto-references between pages
