site_name: PyPty (python + ptychography)
theme:
  name: material
  palette:
    - scheme: slate  # dark mode; use 'default' for light mode
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default  # optional toggle for light mode
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: logo.png
  features:
    - navigation.expand
    - navigation.sections
    - content.code.annotate
    - content.tabs.link  # linkable tabs
repo_url: https://github.com/Anton-Gladyshev/pypty
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - codehilite:
      guess_lang: false
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_style: monokai
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  


plugins:
  - offline
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_inheritance_diagram: true
            show_source: false
            heading_level: 3
            members_order: source
            show_symbol_type_toc: false

            inherited_members: true
            show_labels: true

            docstring_section_style: spacy
            show_signature: false
            separate_signature: false
            docstring_style: numpy



nav:
  - Home: index.md
  - Description of the experiment: experiment.md
  - Examples for iterative ptychography: example_breakdown.md
  - Examples for direct methods: examples_direct.md
  - Guide for creating custom presets: custom_presets.md
  - API Reference:
    - pypty.initialize: reference/initialize.md
    - pypty.dpc: reference/dpc.md
    - pypty.tcbf: reference/tcbf.md
    - pypty.direct: reference/direct.md
    - pypty.iterative: reference/iterative.md
    - pypty.objective: reference/objective.md
    - pypty.multislice_core: reference/multislice_core.md
    - pypty.fft: reference/fft.md
    - pypty.utils: reference/utils.md
    - pypty.se: reference/se.md
    - pypty.vaa: reference/vaa.md


